name: deeptech-international

services:
  backend:
    image: deeptech-international-backend
    build:
        context: backend
    ports:
      - "8502:8501"
    volumes:
      - ./backend:/app
      - files_data:/files
    depends_on:
      - db
  db:
    build:
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: deeptech
      POSTGRES_PASSWORD: deeptech
      POSTGRES_DB: deeptech
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d deeptech -U deeptech" ]
      interval: 5s
      timeout: 60s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - files_data:/usr/share/nginx/static/
    depends_on:
      - backend
volumes:
  db_data:
  files_data: