name: deeptech-international

services:
  backend:
    image: deeptech-international-backend
    build:
        context: backend
    ports:
      - "80:8501"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: deeptech
      POSTGRES_PASSWORD: deeptech
      POSTGRES_DB: deeptech
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d deeptech -U deeptech" ]
      interval: 5s
      timeout: 60s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data: